name: pharesidence
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0


environment:
  sdk: ^3.5.3



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  sizer: ^2.0.15
  mask_text_input_formatter: ^2.9.0
  flutter_svg: ^2.0.10+1
  flutter_otp_text_field: ^1.1.0+2
  cached_network_image: ^3.3.1
  get: ^4.6.6
  dotted_line: ^3.2.2
  http: ^1.2.2
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.6
  flutter_native_splash: 
  cnic_scanner: ^0.0.5
  image_picker: ^1.1.2
  geolocator: ^13.0.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^1.2.0+3
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  cloud_firestore: ^5.4.1
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  dio: ^5.7.0
  flutter_svg_provider: ^1.0.7
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  
  assets:
    - assets/
    - assets/png/
    - assets/svg/

  
  
  fonts:
    - family: BalsamiqSans
      fonts:
        - asset: assets/fonts/BalsamiqSans-Regular.ttf
        - asset: assets/fonts/BalsamiqSans-Bold.ttf
