import 'package:get/get.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import '../../Api_Providers/Api_Responses/api_urls.dart';
import '../../models/projects_models.dart';

class ProjectsViewController extends GetxController {
  var isLoading = true.obs;
  var projects = <Data>[].obs; 

 
  Future<void> fetchProjects(String cnic) async {
    try {
      isLoading(true); 
      final response = await http.get(Uri.parse('$GetCNICByMembership?cnic=$cnic'));

      print('Response status: ${response.statusCode}');
      print('Response body: ${response.body}');

      if (response.statusCode == 200) {
        try {
          final Autogenerated autogenerated = Autogenerated.fromJson(json.decode(response.body));
          if (autogenerated.status == true) {
            projects.assignAll(autogenerated.data!); 
          } else {
        
            Get.snackbar('Error', 'No projects found for this CNIC');
          }
        } catch (jsonError) {
        
          print('JSON decoding error: $jsonError');
          Get.snackbar('Error', 'Failed to decode response');
        }
      } else {
      
        Get.snackbar('Error', 'Failed to fetch projects. Status code: ${response.statusCode}');
      }
    } catch (e) {

      Get.snackbar('Error', 'An error occurred: $e');
      print('Fetch error: $e'); 
    } finally {
      isLoading(false);
    }
  }
}
