class Autogenerated {
  bool? status;
  String? message;
  List<Data>? data;

  Autogenerated({this.status, this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> dataMap = {};
    dataMap['status'] = status;
    dataMap['message'] = message;
    if (data != null) {
      dataMap['data'] = data!.map((v) => v.toJson()).toList();
    }
    return dataMap; 
  }
}

class Data {
  int? id;
  String? registrationNo;
  int? projectId;
  String? fullName;
  String? cnic;
  String? laneNo;
  String? houseNo;
  String? category;
  String? presentAddress;
  String? cell;
  String? status;
  DateTime? createdAt; // Changed to DateTime
  DateTime? updatedAt; // Changed to DateTime
  DateTime? deletedAt; // Changed to DateTime
  String? projectName;

  Data({
    this.id,
    this.registrationNo,
    this.projectId,
    this.fullName,
    this.cnic,
    this.laneNo,
    this.houseNo,
    this.category,
    this.presentAddress,
    this.cell,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.projectName,
  });

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    registrationNo = json['registration_no'];
    projectId = json['project_id'];
    fullName = json['full_name'];
    cnic = json['cnic'];
    laneNo = json['lane_no'];
    houseNo = json['house_no'];
    category = json['category'];
    presentAddress = json['present_address'];
    cell = json['cell'];
    status = json['status'];

    // Parse date strings to DateTime if they are not null
    createdAt = json['created_at'] != null ? DateTime.parse(json['created_at']) : null;
    updatedAt = json['updated_at'] != null ? DateTime.parse(json['updated_at']) : null;
    deletedAt = json['deleted_at'] != null ? DateTime.parse(json['deleted_at']) : null;

    projectName = json['projectName'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> dataMap = {};
    dataMap['id'] = id;
    dataMap['registration_no'] = registrationNo;
    dataMap['project_id'] = projectId;
    dataMap['full_name'] = fullName;
    dataMap['cnic'] = cnic;
    dataMap['lane_no'] = laneNo;
    dataMap['house_no'] = houseNo;
    dataMap['category'] = category;
    dataMap['present_address'] = presentAddress;
    dataMap['cell'] = cell;
    dataMap['status'] = status;

    // Format DateTime objects to ISO 8601 strings for JSON
    dataMap['created_at'] = createdAt?.toIso8601String();
    dataMap['updated_at'] = updatedAt?.toIso8601String();
    dataMap['deleted_at'] = deletedAt?.toIso8601String();

    dataMap['projectName'] = projectName;
    return dataMap;
  }
}

